# Generated by Django 5.1.4 on 2026-09-10 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Идентификатор браузера пользователя без авторизации.', max_length=64, verbose_name='ключ сессии')),
                ('operation', models.CharField(choices=[('add', 'Сложение'), ('subtract', 'Вычитание'), ('multiply', 'Умножение матриц'), ('scalar_multiply', 'Умножение на скаляр'), ('transpose', 'Транспонирование'), ('power', 'Возведение в степень'), ('determinant', 'Определитель'), ('trace', 'След'), ('rank', 'Ранг'), ('inverse', 'Обратная матрица'), ('rref', 'Приведённая ступенчатая форма'), ('echelon', 'Ступенчатая форма'), ('properties', 'Свойства матрицы'), ('eigenvalues', 'Собственные значения'), ('eigenvectors', 'Собственные векторы'), ('char_poly', 'Характеристический многочлен'), ('lu', 'LU-разложение'), ('qr', 'QR-разложение'), ('cholesky', 'Разложение Холецкого'), ('diagonalize', 'Диагонализация'), ('solve_gauss', 'СЛАУ — метод Гаусса'), ('solve_gauss_jordan', 'СЛАУ — метод Гаусса-Жордана'), ('solve_cramer', 'СЛАУ — правило Крамера'), ('solve_inverse', 'СЛАУ — через обратную матрицу'), ('kronecker_capelli', 'Теорема Кронекера-Капелли'), ('minors', 'Минор и алгебраическое дополнение'), ('cofactor_matrix', 'Матрица кофакторов'), ('adjugate', 'Присоединённая матрица'), ('compare', 'Сравнение матриц')], db_index=True, max_length=32, verbose_name='код операции')),
                ('operation_label', models.CharField(blank=True, help_text='Человекочитаемое имя для отображения в списке.', max_length=64, verbose_name='название операции')),
                ('input_data', models.JSONField(default=dict, help_text='Матрицы A, B, скаляры и прочие параметры операции.', verbose_name='входные данные')),
                ('result_data', models.JSONField(default=dict, help_text='Результат операции, шаги решения, проверки.', verbose_name='результат')),
                ('matrix_shape', models.CharField(blank=True, help_text="Например, '3x3' — для быстрого отображения в списке.", max_length=16, verbose_name='размер матрицы')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'запись истории',
                'verbose_name_plural': 'история вычислений',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', '-created_at'], name='matrix_app__session_e46cc9_idx'), models.Index(fields=['operation', '-created_at'], name='matrix_app__operati_f47396_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='ключ сессии')),
                ('name', models.CharField(help_text='Например, «Матрица A из задачи 3.4».', max_length=120, verbose_name='название')),
                ('matrix_data', models.JSONField(default=list, help_text='Двумерный массив строк — точные значения.', verbose_name='данные матрицы')),
                ('rows', models.PositiveSmallIntegerField(default=0, verbose_name='строк')),
                ('cols', models.PositiveSmallIntegerField(default=0, verbose_name='столбцов')),
                ('notes', models.TextField(blank=True, help_text='Свободное описание, зачем эта матрица сохранена.', verbose_name='заметка')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='создано')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'сохранённая матрица',
                'verbose_name_plural': 'сохранённые матрицы',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['session_key', '-updated_at'], name='matrix_app__session_4e996c_idx')],
                'constraints': [models.UniqueConstraint(fields=('session_key', 'name'), name='unique_matrix_name_per_session')],
            },
        ),
    ]
